"""create created_on and updated_on Message Columns

Revision ID: a197f198e8d0
Revises: a036a04fc5a6
Create Date: 2017-11-29 20:00:55.286737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a197f198e8d0'
down_revision = 'a036a04fc5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('messages', sa.Column('updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updated_on')
    op.drop_column('messages', 'created_on')
    # ### end Alembic commands ###
