"""empty message

Revision ID: 89838541ca52
Revises: 32d323b1b2da
Create Date: 2017-12-04 18:28:37.879257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89838541ca52'
down_revision = '32d323b1b2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('username', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
